import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " flex"}>
        <div className="w-1/5">
          <NavBar />
        </div>
        <div className="flex-grow flex flex-col justify-start items-center">
          <div className=" w-4/5">{children}</div>
        </div>
      </body>
    </html>
  );
}
